# Based on a template from http://docs.haskellstack.org/en/stable/GUIDE.html#travis-with-caching
# Use new container infrastructure to enable caching
sudo: false

# Choose a lightweight base image; we provide our own build tools.
language: c

# GHC depends on GMP. You can add other dependencies here as well.
addons:
  apt:
    packages:
    - libgmp-dev

# The different configurations we want to test. You could also do things like
# change flags or use --stack-yaml to point to a different file.

# The stack.lts2.yaml file is required because LTS2 uses a version of doctest that
# is too old to run our test suite.
env:
- ARGS="--stack-yaml stack.ghc84.yaml"
  #- ARGS="--resolver lts-2 --stack-yaml stack.lts2.yaml"
  #- ARGS="--resolver lts-3 --stack-yaml stack.lts3.yaml"
  #- ARGS="--resolver lts-5 --stack-yaml stack.lts5.yaml"
  #- ARGS="--resolver lts-6 --stack-yaml stack.yaml"
  #- ARGS="--resolver lts-7 --stack-yaml stack.lts7.yaml"
  #- ARGS="--resolver lts-9 --stack-yaml stack.lts9.yaml"
  #- ARGS="--resolver lts-10 --stack-yaml stack.lts10.yaml"

before_install:
# Download and unpack the stack executable
- sudo ln -s /lib/libncurses.so.6 /usr/lib/libtinfo.so.6
- sudo ln -s /usr/lib/libtinfo.so.6 /usr/lib/libtinfo.so
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
# Ask stack to install GHC
- stack $ARGS setup
# Ask stack to install hscolour for haddock source colorization.
- stack $ARGS install hscolour

# This line does all of the work: build the library,
# executables, and test suites, and runs the test suites. --no-terminal works
# around some quirks in Travis's terminal implementation.
script: stack $ARGS --no-terminal test --haddock --no-haddock-deps --bench

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack
